// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface Player {
  UUID: string;
  Health: number /* float64 */;
  Absorption: number /* float64 */;
  XPLevel: number /* int */;
  XPTotal: number /* int */;
  XPProgress: number /* float64 */;
  FoodLevel: number /* int */;
  Saturation: number /* float64 */;
  Exhaustion: number /* float64 */;
  FallDistance: number /* float64 */;
  OnGround: boolean;
  Gamemode: number /* int */;
  Pos: number /* float64 */[];
  Motion: number /* float64 */[];
  Rotation: number /* float64 */[];
  Dimension: string;
  Inventory: Item[];
  EnderChest: Item[];
  Selected: Item;
  SelectedSlot: number /* int */;
  Abilities: { [key: string]: any};
  Attributes: Attribute[];
  LastSeen: number /* int64 */;
  Flags: { [key: string]: any};
}
export interface Item {
  ID: string;
  Count: number /* int */;
  Slot: number /* int */;
  Damage: number /* int */;
}
export interface Attribute {
  Name: string;
  Value: number /* float64 */;
}
