// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

export interface MsgFormat {
  type: string;
  status: string;
  payload: any;
}
export interface FileInfo {
  name: string;
  type: string;
  size: number /* int64 */;
  ext: string;
  path: string;
}
