// Code generated by tygo. DO NOT EDIT.

//////////
// source: handlers.go

export interface CreateTunnelReq {
  name: string;
  tunnel_type: string;
  port_type: string;
  port_count: number /* int */;
  port: number /* int */;
}
export interface Player {
  uuid: string;
  name: string;
  expiresOn: string;
}
